
const stats_table_ = [
        {eid:0,name:"Intelect",use_for_sorting:true},
        {eid:1,name:"Spell Power",use_for_sorting:true},
        {eid:2,name:"Hit",use_for_sorting:true},
        {eid:3,name:"Haste",use_for_sorting:true},
        {eid:4,name:"Critical Strike Rating",use_for_sorting:true},
        {eid:5,name:"Strength",use_for_sorting:true},
        {eid:6,name:"Attack Power",use_for_sorting:true},
        {eid:7,name:"Agility",use_for_sorting:true},
        {eid:8,name:"Parry Rating",use_for_sorting:true},
        {eid:9,name:"Armor Penetration Rating",use_for_sorting:true},
        {eid:10,name:"Expertise Rating",use_for_sorting:true},
        {eid:11,name:"Dodge Rating",use_for_sorting:true},
        {eid:12,name:"Mp5",use_for_sorting:true},
        {eid:13,name:"Stamina",use_for_sorting:true},
        {eid:14,name:"Spirit",use_for_sorting:true},
        {eid:15,name:"Spell Penetration",use_for_sorting:true},
        {eid:16,name:"Resiliance Rating",use_for_sorting:true},
        {eid:17,name:"Defense Rating",use_for_sorting:true},
        {eid:19,name:"Armor Value",use_for_sorting:false},
        {eid:20,name:"Mana",use_for_sorting:false},
        {eid:21,name:"Critical Damage",use_for_sorting:false},
        {eid:22,name:"Spell Reflect",use_for_sorting:false},
        {eid:23,name:"Spell Damage Taken",use_for_sorting:false},
        {eid:24,name:"Snare/Root Duration",use_for_sorting:false},
        {eid:25,name:"Shield Block Value",use_for_sorting:false},
        {eid:26,name:"Silence Duration",use_for_sorting:false},
        {eid:27,name:"Fear Duration",use_for_sorting:false},
        {eid:28,name:"Change to Restore Mana on Spell Cast",use_for_sorting:false},
        {eid:29,name:"Change to Heal on Critical Strikes",use_for_sorting:false},
        {eid:30,name:"Stun Duration",use_for_sorting:false},
        {eid:31,name:"Critical Healing",use_for_sorting:false},
        {eid:32,name:"Run Speed",use_for_sorting:false},
        {eid:33,name:"Threat",use_for_sorting:false},
];

const color_table_ = [
    {eid: 0, name: "Red",use_for_sorting:true},
    {eid: 1, name: "Blue",use_for_sorting:true},
    {eid: 2, name: "Yellow",use_for_sorting:true},
    {eid: 3, name: "Meta",use_for_sorting:true},
];

const size_table_ = [
    {eid: 0, name: "Small",use_for_sorting:true},
    {eid: 1, name: "Medium",use_for_sorting:true},
    {eid: 2, name: "Large",use_for_sorting:true},
    {eid: 3, name: "Jewelcrafting",use_for_sorting:true},
    {eid: 4, name: "Meta",use_for_sorting:true}
];

const gem_table_ = [
    {name: "Bold Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:5,amount:12,percentage:false}], wowhead_item_id:39900},
    {name: "Perfect Bold Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:5,amount:14,percentage:false}], wowhead_item_id:41432},
    {name: "Bold Cardinal Ruby", socket_color:[0], gem_size:2, gem_stats:[{eid:5,amount:20,percentage:false}], wowhead_item_id:40111},
    {name: "Bold Dragon's Eye", socket_color:[0], gem_size:3, gem_stats:[{eid:5,amount:34,percentage:false}], wowhead_item_id:42142},
    {name: "Bold Scarlet Ruby", socket_color:[0], gem_size:1, gem_stats:[{eid:5,amount:16,percentage:false}], wowhead_item_id:39996},
    {name: "Bold Stormjewel", socket_color:[0], gem_size:2, gem_stats:[{eid:5,amount:20,percentage:false}], wowhead_item_id:45862},

    {name: "Bright Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:6,amount:24,percentage:false}], wowhead_item_id:39906},
    {name: "Perfect Bright Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:6,amount:28,percentage:false}], wowhead_item_id:41433},
    {name: "Bright Cardinal Ruby", socket_color:[0], gem_size:2, gem_stats:[{eid:6,amount:40,percentage:false}], wowhead_item_id:40114},
    {name: "Bright Dragon's Eye", socket_color:[0], gem_size:3, gem_stats:[{eid:6,amount:68,percentage:false}], wowhead_item_id:36766},
    {name: "Bright Scarlet Ruby", socket_color:[0], gem_size:1, gem_stats:[{eid:6,amount:32,percentage:false}], wowhead_item_id:39999},

    {name: "Delicate Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:7,amount:12,percentage:false}], wowhead_item_id:39905},
    {name: "Perfect Delicate Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:7,amount:14,percentage:false}], wowhead_item_id:41434},
    {name: "Delicate Cardinal Ruby", socket_color:[0], gem_size:2, gem_stats:[{eid:7,amount:20,percentage:false}], wowhead_item_id:40112},
    {name: "Delicate Dragon's Eye", socket_color:[0], gem_size:3, gem_stats:[{eid:7,amount:34,percentage:false}], wowhead_item_id:42143},
    {name: "Delicate Scarlet Ruby", socket_color:[0], gem_size:1, gem_stats:[{eid:7,amount:16,percentage:false}], wowhead_item_id:39997},
    {name: "Delicate Stormjewel", socket_color:[0], gem_size:2, gem_stats:[{eid:7,amount:20,percentage:false}], wowhead_item_id:45879},

    {name: "Flashing Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:8,amount:12,percentage:false}], wowhead_item_id:39908},
    {name: "Perfect Flashing Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:8,amount:14,percentage:false}], wowhead_item_id:41435},
    {name: "Flashing Cardinal Ruby", socket_color:[0], gem_size:2, gem_stats:[{eid:8,amount:20,percentage:false}], wowhead_item_id:40116},
    {name: "Flashing Dragon's Eye", socket_color:[0], gem_size:3, gem_stats:[{eid:8,amount:34,percentage:false}], wowhead_item_id:42152},
    {name: "Flashing Scarlet Ruby", socket_color:[0], gem_size:1, gem_stats:[{eid:8,amount:16,percentage:false}], wowhead_item_id:40001},

    {name: "Fractured Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:9,amount:12,percentage:false}], wowhead_item_id:39909},
    {name: "Perfect Fractured Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:9,amount:14,percentage:false}], wowhead_item_id:41436},
    {name: "Fractured Cardinal Ruby", socket_color:[0], gem_size:2, gem_stats:[{eid:9,amount:20,percentage:false}], wowhead_item_id:40117},
    {name: "Fractured Dragon's Eye", socket_color:[0], gem_size:3, gem_stats:[{eid:9,amount:34,percentage:false}], wowhead_item_id:42153},
    {name: "Fractured Scarlet Ruby", socket_color:[0], gem_size:1, gem_stats:[{eid:9,amount:16,percentage:false}], wowhead_item_id:40002},

    {name: "Precise Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:10,amount:12,percentage:false}], wowhead_item_id:39910},
    {name: "Perfect Precise Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:10,amount:14,percentage:false}], wowhead_item_id:41437},
    {name: "Precise Cardinal Ruby", socket_color:[0], gem_size:2, gem_stats:[{eid:10,amount:20,percentage:false}], wowhead_item_id:40118},
    {name: "Precise Dragon's Eye", socket_color:[0], gem_size:3, gem_stats:[{eid:10,amount:34,percentage:false}], wowhead_item_id:42154},
    {name: "Precise Scarlet Ruby", socket_color:[0], gem_size:1, gem_stats:[{eid:10,amount:16,percentage:false}], wowhead_item_id:40003},

    {name: "Runed Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:1,amount:14,percentage:false}], wowhead_item_id:39911},
    {name: "Perfect Runed Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:1,amount:16,percentage:false}], wowhead_item_id:41438},
    {name: "Runed Cardinal Ruby", socket_color:[0], gem_size:2, gem_stats:[{eid:1,amount:23,percentage:false}], wowhead_item_id:40113},
    {name: "Runed Dragon's Eye", socket_color:[0], gem_size:3, gem_stats:[{eid:1,amount:39,percentage:false}], wowhead_item_id:42144},
    {name: "Runed Scarlet Ruby", socket_color:[0], gem_size:1, gem_stats:[{eid:1,amount:19,percentage:false}], wowhead_item_id:39998},
    {name: "Runed Stormjewel", socket_color:[0], gem_size:2, gem_stats:[{eid:1,amount:23,percentage:false}], wowhead_item_id:45883},

    {name: "Subtle Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:11,amount:12,percentage:false}], wowhead_item_id:39907},
    {name: "Perfect Subtle Bloodstone", socket_color:[0], gem_size:0, gem_stats:[{eid:11,amount:14,percentage:false}], wowhead_item_id:41439},
    {name: "Subtle Cardinal Ruby", socket_color:[0], gem_size:2, gem_stats:[{eid:11,amount:20,percentage:false}], wowhead_item_id:40115},
    {name: "Subtle Dragon's Eye", socket_color:[0], gem_size:3, gem_stats:[{eid:11,amount:34,percentage:false}], wowhead_item_id:42151},
    {name: "Subtle Scarlet Ruby", socket_color:[0], gem_size:1, gem_stats:[{eid:11,amount:16,percentage:false}], wowhead_item_id:40000},

    {name: "Lustrous Chalcedony", socket_color:[1], gem_size:0, gem_stats:[{eid:12,amount:6,percentage:false}], wowhead_item_id:39927},
    {name: "Perfect Lustrous Chalcedony", socket_color:[1], gem_size:0, gem_stats:[{eid:12,amount:7,percentage:false}], wowhead_item_id:41440},
    {name: "Lustrous Majestic Zircon", socket_color:[1], gem_size:2, gem_stats:[{eid:12,amount:10,percentage:false}], wowhead_item_id:40121},
    {name: "Lustrous Dragon's Eye", socket_color:[1], gem_size:3, gem_stats:[{eid:12,amount:17,percentage:false}], wowhead_item_id:42146},
    {name: "Lustrous Sky Sapphire", socket_color:[1], gem_size:1, gem_stats:[{eid:12,amount:8,percentage:false}], wowhead_item_id:40010},

    {name: "Solid Chalcedony", socket_color:[1], gem_size:0, gem_stats:[{eid:13,amount:18,percentage:false}], wowhead_item_id:39919},
    {name: "Perfect Solid Chalcedony", socket_color:[1], gem_size:0, gem_stats:[{eid:13,amount:21,percentage:false}], wowhead_item_id:41441},
    {name: "Solid Majestic Zircon", socket_color:[1], gem_size:2, gem_stats:[{eid:13,amount:30,percentage:false}], wowhead_item_id:40119},
    {name: "Solid Dragon's Eye", socket_color:[1], gem_size:3, gem_stats:[{eid:13,amount:51,percentage:false}], wowhead_item_id:36767},
    {name: "Solid Sky Sapphire", socket_color:[1], gem_size:1, gem_stats:[{eid:13,amount:24,percentage:false}], wowhead_item_id:40008},
    {name: "Solid Stormjewel", socket_color:[1], gem_size:2, gem_stats:[{eid:13,amount:30,percentage:false}], wowhead_item_id:45880},

    {name: "Sparkling Chalcedony", socket_color:[1], gem_size:0, gem_stats:[{eid:14,amount:12,percentage:false}], wowhead_item_id:39920},
    {name: "Perfect Sparkling Chalcedony", socket_color:[1], gem_size:0, gem_stats:[{eid:14,amount:14,percentage:false}], wowhead_item_id:41442},
    {name: "Sparkling Majestic Zircon", socket_color:[1], gem_size:2, gem_stats:[{eid:14,amount:20,percentage:false}], wowhead_item_id:40120},
    {name: "Sparkling Dragon's Eye", socket_color:[1], gem_size:3, gem_stats:[{eid:14,amount:34,percentage:false}], wowhead_item_id:42145},
    {name: "Sparkling Sky Sapphire", socket_color:[1], gem_size:1, gem_stats:[{eid:14,amount:16,percentage:false}], wowhead_item_id:40009},
    {name: "Sparkling Stormjewel", socket_color:[1], gem_size:2, gem_stats:[{eid:14,amount:20,percentage:false}], wowhead_item_id:45881},

    {name: "Stormy Chalcedony", socket_color:[1], gem_size:0, gem_stats:[{eid:15,amount:15,percentage:false}], wowhead_item_id:39932},
    {name: "Perfect Stormy Chalcedony", socket_color:[1], gem_size:0, gem_stats:[{eid:15,amount:18,percentage:false}], wowhead_item_id:41443},
    {name: "Stormy Majestic Zircon", socket_color:[1], gem_size:2, gem_stats:[{eid:15,amount:25,percentage:false}], wowhead_item_id:40122},
    {name: "Stormy Dragon's Eye", socket_color:[1], gem_size:3, gem_stats:[{eid:15,amount:43,percentage:false}], wowhead_item_id:42155},
    {name: "Stormy Sky Sapphire", socket_color:[1], gem_size:1, gem_stats:[{eid:15,amount:20,percentage:false}], wowhead_item_id:40011},

    {name: "Brilliant Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:0,amount:12,percentage:false}], wowhead_item_id:39912},
    {name: "Perfect Brilliant Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:0,amount:14,percentage:false}], wowhead_item_id:41444},
    {name: "Brilliant King's Amber", socket_color:[2], gem_size:2, gem_stats:[{eid:0,amount:20,percentage:false}], wowhead_item_id:40123},
    {name: "Brilliant Dragon's Eye", socket_color:[2], gem_size:3, gem_stats:[{eid:0,amount:34,percentage:false}], wowhead_item_id:42148},
    {name: "Brilliant Autumn's Glow", socket_color:[2], gem_size:1, gem_stats:[{eid:0,amount:16,percentage:false}], wowhead_item_id:40012},
    {name: "Brilliant Stormjewel", socket_color:[2], gem_size:2, gem_stats:[{eid:0,amount:20,percentage:false}], wowhead_item_id:45882},

    {name: "Mystic Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:16,amount:12,percentage:false}], wowhead_item_id:39917},
    {name: "Perfect Mystic Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:16,amount:14,percentage:false}], wowhead_item_id:41445},
    {name: "Mystic King's Amber", socket_color:[2], gem_size:2, gem_stats:[{eid:16,amount:20,percentage:false}], wowhead_item_id:40127},
    {name: "Mystic Dragon's Eye", socket_color:[2], gem_size:3, gem_stats:[{eid:16,amount:34,percentage:false}], wowhead_item_id:42158},
    {name: "Mystic Autumn's Glow", socket_color:[2], gem_size:1, gem_stats:[{eid:16,amount:16,percentage:false}], wowhead_item_id:40016},
    {name: "Kharmaa's Grace", socket_color:[2], gem_size:2, gem_stats:[{eid:16,amount:20,percentage:false}], wowhead_item_id:44066},

    {name: "Quick Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:3,amount:12,percentage:false}], wowhead_item_id:39918},
    {name: "Perfect Quick Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:3,amount:14,percentage:false}], wowhead_item_id:41446},
    {name: "Quick King's Amber", socket_color:[2], gem_size:2, gem_stats:[{eid:3,amount:20,percentage:false}], wowhead_item_id:40128},
    {name: "Quick Dragon's Eye", socket_color:[2], gem_size:3, gem_stats:[{eid:3,amount:34,percentage:false}], wowhead_item_id:42150},
    {name: "Quick Autumn's Glow", socket_color:[2], gem_size:1, gem_stats:[{eid:3,amount:16,percentage:false}], wowhead_item_id:40017},

    {name: "Rigid Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:2,amount:12,percentage:false}], wowhead_item_id:39915},
    {name: "Perfect Rigid Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:2,amount:14,percentage:false}], wowhead_item_id:41447},
    {name: "Rigid King's Amber", socket_color:[2], gem_size:2, gem_stats:[{eid:2,amount:20,percentage:false}], wowhead_item_id:40125},
    {name: "Rigid Dragon's Eye", socket_color:[2], gem_size:3, gem_stats:[{eid:2,amount:34,percentage:false}], wowhead_item_id:42156},
    {name: "Rigid Autumn's Glow", socket_color:[2], gem_size:1, gem_stats:[{eid:2,amount:16,percentage:false}], wowhead_item_id:40014},
    {name: "Rigid Stormjewel", socket_color:[2], gem_size:2, gem_stats:[{eid:2,amount:20,percentage:false}], wowhead_item_id:45987},

    {name: "Smooth Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:4,amount:12,percentage:false}], wowhead_item_id:39914},
    {name: "Perfect Smooth Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:4,amount:14,percentage:false}], wowhead_item_id:41448},
    {name: "Smooth King's Amber", socket_color:[2], gem_size:2, gem_stats:[{eid:4,amount:20,percentage:false}], wowhead_item_id:40124},
    {name: "Smooth Dragon's Eye", socket_color:[2], gem_size:3, gem_stats:[{eid:4,amount:34,percentage:false}], wowhead_item_id:42149},
    {name: "Smooth Autumn's Glow", socket_color:[2], gem_size:1, gem_stats:[{eid:4,amount:16,percentage:false}], wowhead_item_id:40013},

    {name: "Thick Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:17,amount:12,percentage:false}], wowhead_item_id:39916},
    {name: "Perfect Thick Sun Crystal", socket_color:[2], gem_size:0, gem_stats:[{eid:17,amount:14,percentage:false}], wowhead_item_id:41449},
    {name: "Thick King's Amber", socket_color:[2], gem_size:2, gem_stats:[{eid:17,amount:20,percentage:false}], wowhead_item_id:40126},
    {name: "Thick Dragon's Eye", socket_color:[2], gem_size:3, gem_stats:[{eid:17,amount:34,percentage:false}], wowhead_item_id:42157},
    {name: "Thick Autumn's Glow", socket_color:[2], gem_size:1, gem_stats:[{eid:17,amount:16,percentage:false}], wowhead_item_id:40015},

    {name: "Accurate Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:10,amount:6,percentage:false}, {eid:2,amount:6,percentage:false}], wowhead_item_id:39966},
    {name: "Accurate Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:10,amount:8,percentage:false}, {eid:2,amount:8,percentage:false}], wowhead_item_id:40058},
    {name: "Accurate Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:10,amount:10,percentage:false}, {eid:2,amount:10,percentage:false}], wowhead_item_id:40162},

    {name: "Champion's Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:6,percentage:false}, {eid:17,amount:6,percentage:false}], wowhead_item_id:39949},
    {name: "Perfect Champion's Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:7,percentage:false}, {eid:17,amount:7,percentage:false}], wowhead_item_id:41483},
    {name: "Champion's Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:5,amount:8,percentage:false}, {eid:17,amount:8,percentage:false}], wowhead_item_id:40039},
    {name: "Champion's Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:5,amount:10,percentage:false}, {eid:17,amount:10,percentage:false}], wowhead_item_id:40144},

    {name: "Deadly Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:7,amount:6,percentage:false}, {eid:4,amount:6,percentage:false}], wowhead_item_id:39952},
    {name: "Perfect Deadly Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:7,amount:7,percentage:false}, {eid:4,amount:7,percentage:false}], wowhead_item_id:41484},
    {name: "Deadly Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:7,amount:8,percentage:false}, {eid:4,amount:8,percentage:false}], wowhead_item_id:40043},
    {name: "Deadly Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:7,amount:10,percentage:false}, {eid:4,amount:10,percentage:false}], wowhead_item_id:40147},

    {name: "Deft Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:7,amount:6,percentage:false}, {eid:3,amount:6,percentage:false}], wowhead_item_id:39955},
    {name: "Perfect Deft Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:7,amount:7,percentage:false}, {eid:3,amount:7,percentage:false}], wowhead_item_id:41485},
    {name: "Deft Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:7,amount:8,percentage:false}, {eid:3,amount:8,percentage:false}], wowhead_item_id:40046},
    {name: "Deft Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:7,amount:10,percentage:false}, {eid:3,amount:10,percentage:false}], wowhead_item_id:40150},

    {name: "Durable Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:6,percentage:false}, {eid:16,amount:4,percentage:false}], wowhead_item_id:39958},
    {name: "Perfect Durable Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:16,amount:7,percentage:false}], wowhead_item_id:41486},
    {name: "Durable Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:16,amount:8,percentage:false}], wowhead_item_id:40050},
    {name: "Durable Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:16,amount:10,percentage:false}], wowhead_item_id:40154},

    {name: "Empowered Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:6,amount:12,percentage:false}, {eid:16,amount:6,percentage:false}], wowhead_item_id:39962},
    {name: "Perfect Empowered Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:6,amount:14,percentage:false}, {eid:16,amount:7,percentage:false}], wowhead_item_id:41487},
    {name: "Empowered Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:6,amount:16,percentage:false}, {eid:16,amount:8,percentage:false}], wowhead_item_id:40054},
    {name: "Empowered Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:6,amount:20,percentage:false}, {eid:16,amount:10,percentage:false}], wowhead_item_id:40158},

    {name: "Etched Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:6,percentage:false}, {eid:2,amount:6,percentage:false}], wowhead_item_id:39948},
    {name: "Perfect Etched Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:7,percentage:false}, {eid:2,amount:7,percentage:false}], wowhead_item_id:41488},
    {name: "Etched Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:5,amount:8,percentage:false}, {eid:2,amount:8,percentage:false}], wowhead_item_id:40038},
    {name: "Etched Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:5,amount:10,percentage:false}, {eid:2,amount:10,percentage:false}], wowhead_item_id:40143},

    {name: "Fierce Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:6,percentage:false}, {eid:3,amount:6,percentage:false}], wowhead_item_id:39951},
    {name: "Perfect Fierce Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:7,percentage:false}, {eid:3,amount:7,percentage:false}], wowhead_item_id:41489},
    {name: "Fierce Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:5,amount:8,percentage:false}, {eid:3,amount:8,percentage:false}], wowhead_item_id:40041},
    {name: "Fierce Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:5,amount:10,percentage:false}, {eid:3,amount:10,percentage:false}], wowhead_item_id:40146},

    {name: "Glimmering Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:8,amount:6,percentage:false}, {eid:17,amount:6,percentage:false}], wowhead_item_id:39965},
    {name: "Perfect Glimmering Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:8,amount:7,percentage:false}, {eid:17,amount:7,percentage:false}], wowhead_item_id:41490},
    {name: "Glimmering Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:8,amount:8,percentage:false}, {eid:17,amount:8,percentage:false}], wowhead_item_id:40057},
    {name: "Glimmering Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:8,amount:10,percentage:false}, {eid:17,amount:10,percentage:false}], wowhead_item_id:40161},

    {name: "Glinting Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:7,amount:6,percentage:false}, {eid:2,amount:6,percentage:false}], wowhead_item_id:39953},
    {name: "Perfect Glinting Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:7,amount:7,percentage:false}, {eid:2,amount:7,percentage:false}], wowhead_item_id:41491},
    {name: "Glinting Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:7,amount:8,percentage:false}, {eid:2,amount:8,percentage:false}], wowhead_item_id:40044},
    {name: "Glinting Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:7,amount:10,percentage:false}, {eid:2,amount:10,percentage:false}], wowhead_item_id:40148},

    {name: "Inscribed Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:6,percentage:false}, {eid:4,amount:6,percentage:false}], wowhead_item_id:39947},
    {name: "Perfect Inscribed Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:7,percentage:false}, {eid:4,amount:7,percentage:false}], wowhead_item_id:41492},
    {name: "Inscribed Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:5,amount:8,percentage:false}, {eid:4,amount:8,percentage:false}], wowhead_item_id:40037},
    {name: "Inscribed Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:5,amount:10,percentage:false}, {eid:4,amount:10,percentage:false}], wowhead_item_id:40142},

    {name: "Lucent Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:7,amount:6,percentage:false}, {eid:16,amount:6,percentage:false}], wowhead_item_id:39954},
    {name: "Perfect Lucent Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:7,amount:7,percentage:false}, {eid:16,amount:7,percentage:false}], wowhead_item_id:41493},
    {name: "Lucent Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:7,amount:8,percentage:false}, {eid:16,amount:8,percentage:false}], wowhead_item_id:40045},
    {name: "Lucent Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:7,amount:10,percentage:false}, {eid:16,amount:10,percentage:false}], wowhead_item_id:40149},

    {name: "Luminous Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:0,amount:6,percentage:false}], wowhead_item_id:39946},
    {name: "Perfect Luminous Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:0,amount:7,percentage:false}], wowhead_item_id:41494},
    {name: "Luminous Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:0,amount:8,percentage:false}], wowhead_item_id:40047},
    {name: "Luminous Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:0,amount:10,percentage:false}], wowhead_item_id:40151},

    {name: "Potent Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:4,amount:6,percentage:false}], wowhead_item_id:39956},
    {name: "Perfect Potent Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:4,amount:7,percentage:false}], wowhead_item_id:41495},
    {name: "Potent Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:4,amount:8,percentage:false}], wowhead_item_id:40048},
    {name: "Potent Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:4,amount:10,percentage:false}], wowhead_item_id:40152},

    {name: "Pristine Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:6,amount:12,percentage:false}, {eid:2,amount:6,percentage:false}], wowhead_item_id:39961},
    {name: "Perfect Pristine Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:6,amount:14,percentage:false}, {eid:2,amount:7,percentage:false}], wowhead_item_id:41496},
    {name: "Pristine Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:6,amount:16,percentage:false}, {eid:2,amount:8,percentage:false}], wowhead_item_id:40053},
    {name: "Pristine Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:6,amount:20,percentage:false}, {eid:2,amount:10,percentage:false}], wowhead_item_id:40157},

    {name: "Reckless Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:3,amount:6,percentage:false}], wowhead_item_id:39959},
    {name: "Perfect Reckless Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:3,amount:7,percentage:false}], wowhead_item_id:41497},
    {name: "Reckless Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:3,amount:8,percentage:false}], wowhead_item_id:40051},
    {name: "Reckless Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:3,amount:10,percentage:false}], wowhead_item_id:40155},

    {name: "Resolute Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:10,amount:6,percentage:false}, {eid:17,amount:6,percentage:false}], wowhead_item_id:39967},
    {name: "Perfect Resolute Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:10,amount:7,percentage:false}, {eid:17,amount:7,percentage:false}], wowhead_item_id:41498},
    {name: "Resolute Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:10,amount:8,percentage:false}, {eid:17,amount:8,percentage:false}], wowhead_item_id:40059},
    {name: "Resolute Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:10,amount:10,percentage:false}, {eid:17,amount:10,percentage:false}], wowhead_item_id:40163},

    {name: "Resplendent Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:6,percentage:false}, {eid:16,amount:6,percentage:false}], wowhead_item_id:39950},
    {name: "Perfect Resplendent Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:5,amount:7,percentage:false}, {eid:16,amount:7,percentage:false}], wowhead_item_id:41499},
    {name: "Resplendent Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:5,amount:8,percentage:false}, {eid:16,amount:8,percentage:false}], wowhead_item_id:40040},
    {name: "Resplendent Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:5,amount:10,percentage:false}, {eid:16,amount:10,percentage:false}], wowhead_item_id:40145},

    {name: "Stalwart Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:11,amount:6,percentage:false}, {eid:17,amount:6,percentage:false}], wowhead_item_id:39964},
    {name: "Perfect Stalwart Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:11,amount:7,percentage:false}, {eid:17,amount:7,percentage:false}], wowhead_item_id:41500},
    {name: "Stalwart Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:11,amount:8,percentage:false}, {eid:17,amount:8,percentage:false}], wowhead_item_id:40056},
    {name: "Stalwart Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:11,amount:10,percentage:false}, {eid:17,amount:10,percentage:false}], wowhead_item_id:40160},

    {name: "Stark Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:6,amount:12,percentage:false}, {eid:3,amount:6,percentage:false}], wowhead_item_id:39963},
    {name: "Perfect Stark Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:6,amount:14,percentage:false}, {eid:3,amount:7,percentage:false}], wowhead_item_id:41501},
    {name: "Stark Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:6,amount:16,percentage:false}, {eid:3,amount:8,percentage:false}], wowhead_item_id:40055},
    {name: "Stark Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:6,amount:20,percentage:false}, {eid:3,amount:10,percentage:false}], wowhead_item_id:40159},

    {name: "Veiled Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:2,amount:6,percentage:false}], wowhead_item_id:39957},
    {name: "Perfect Veiled Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:2,amount:7,percentage:false}], wowhead_item_id:41502},
    {name: "Veiled Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:2,amount:8,percentage:false}], wowhead_item_id:40049},
    {name: "Veiled Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:2,amount:10,percentage:false}], wowhead_item_id:40153},

    {name: "Wicked Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:6,amount:12,percentage:false}, {eid:4,amount:6,percentage:false}], wowhead_item_id:39960},
    {name: "Perfect Wicked Huge Citrine", socket_color:[0,2], gem_size:0, gem_stats:[{eid:6,amount:14,percentage:false}, {eid:4,amount:7,percentage:false}], wowhead_item_id:41429},
    {name: "Wicked Monarch Topaz", socket_color:[0,2], gem_size:1, gem_stats:[{eid:6,amount:16,percentage:false}, {eid:4,amount:8,percentage:false}], wowhead_item_id:40052},
    {name: "Wicked Ametrine", socket_color:[0,2], gem_size:2, gem_stats:[{eid:6,amount:20,percentage:false}, {eid:4,amount:10,percentage:false}], wowhead_item_id:40156},

    {name: "Balanced Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:6,amount:12,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39937},
    {name: "Perfect Balanced Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:6,amount:14,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41450},
    {name: "Balanced Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:6,amount:16,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40029},
    {name: "Balanced Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:6,amount:20,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40136},

    {name: "Defender's Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:8,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39939},
    {name: "Perfect Defender's Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:8,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41451},
    {name: "Defender's Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:8,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40032},
    {name: "Defender's Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:8,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40139},

    {name: "Glowing Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39936},
    {name: "Perfect Glowing Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41452},
    {name: "Glowing Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40025},
    {name: "Glowing Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40132},

    {name: "Guardian's Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:10,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39940},
    {name: "Perfect Guardian's Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:10,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41453},
    {name: "Guardian's Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:10,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40034},
    {name: "Guardian's Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:10,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40141},

    {name: "Infused Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:6,amount:12,percentage:false}, {eid:12,amount:3,percentage:false}], wowhead_item_id:39944},
    {name: "Perfect Infused Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:6,amount:14,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:41454},
    {name: "Infused Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:6,amount:16,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:40030},
    {name: "Infused Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:6,amount:20,percentage:false}, {eid:12,amount:5,percentage:false}], wowhead_item_id:40137},

    {name: "Mysterious Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:15,amount:8,percentage:false}], wowhead_item_id:39945},
    {name: "Perfect Mysterious Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:15,amount:9,percentage:false}], wowhead_item_id:41455},
    {name: "Mysterious Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:15,amount:10,percentage:false}], wowhead_item_id:40028},
    {name: "Mysterious Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:15,amount:13,percentage:false}], wowhead_item_id:40135},

    {name: "Mysterious Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:15,amount:8,percentage:false}], wowhead_item_id:39945},
    {name: "Perfect Mysterious Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:15,amount:9,percentage:false}], wowhead_item_id:41455},
    {name: "Mysterious Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:15,amount:10,percentage:false}], wowhead_item_id:40028},
    {name: "Mysterious Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:15,amount:13,percentage:false}], wowhead_item_id:40135},

    {name: "Puissant Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:9,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39933},
    {name: "Perfect Puissant Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:9,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41456},
    {name: "Puissant Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:9,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40033},
    {name: "Puissant Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:9,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40140},

    {name: "Purified Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:14,amount:6,percentage:false}], wowhead_item_id:39941},
    {name: "Perfect Purified Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:14,amount:7,percentage:false}], wowhead_item_id:41457},
    {name: "Purified Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:14,amount:8,percentage:false}], wowhead_item_id:40026},
    {name: "Purified Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:14,amount:10,percentage:false}], wowhead_item_id:40133},

    {name: "Purified Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:14,amount:6,percentage:false}], wowhead_item_id:39941},
    {name: "Perfect Purified Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:14,amount:7,percentage:false}], wowhead_item_id:41457},
    {name: "Purified Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:14,amount:8,percentage:false}], wowhead_item_id:40026},
    {name: "Purified Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:14,amount:10,percentage:false}], wowhead_item_id:40133},

    {name: "Regal Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:11,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39938},
    {name: "Perfect Regal Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:11,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41458},
    {name: "Regal Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:11,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40031},
    {name: "Regal Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:11,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40138},

    {name: "Royal Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:7,percentage:false}, {eid:12,amount:3,percentage:false}], wowhead_item_id:39943},
    {name: "Perfect Royal Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:1,amount:8,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:41459},
    {name: "Royal Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:1,amount:9,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:40027},
    {name: "Royal Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:1,amount:12,percentage:false}, {eid:12,amount:5,percentage:false}], wowhead_item_id:40134},

    {name: "Shifting Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:7,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39935},
    {name: "Perfect Shifting Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:7,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41460},
    {name: "Shifting Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:7,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40023},
    {name: "Shifting Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:7,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40130},
    
    {name: "Sovereign Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:5,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39934},
    {name: "Perfect Sovereign Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:5,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41461},
    {name: "Sovereign Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:5,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40022},
    {name: "Sovereign Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:5,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40129},

    {name: "Tenuous Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:7,amount:6,percentage:false}, {eid:12,amount:3,percentage:false}], wowhead_item_id:39942},
    {name: "Perfect Tenuous Shadow Crystal", socket_color:[0,1], gem_size:0, gem_stats:[{eid:7,amount:7,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:41462},
    {name: "Tenuous Twilight Opal", socket_color:[0,1], gem_size:1, gem_stats:[{eid:7,amount:8,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:40024},
    {name: "Tenuous Dreadstone", socket_color:[0,1], gem_size:2, gem_stats:[{eid:7,amount:10,percentage:false}, {eid:12,amount:5,percentage:false}], wowhead_item_id:40131},

    {name: "Dazzling Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:0,amount:6,percentage:false}, {eid:12,amount:3,percentage:false}], wowhead_item_id:39984},
    {name: "Perfect Dazzling Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:0,amount:7,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:41463},
    {name: "Dazzling Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:0,amount:8,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:40094},
    {name: "Dazzling Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:0,amount:10,percentage:false}, {eid:12,amount:5,percentage:false}], wowhead_item_id:40175},

    {name: "Enduring Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:17,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39976},
    {name: "Perfect Enduring Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:17,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41464},
    {name: "Enduring Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:17,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40089},
    {name: "Enduring Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:17,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40167},

    {name: "Energized Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:3,amount:6,percentage:false}, {eid:12,amount:3,percentage:false}], wowhead_item_id:39989},
    {name: "Perfect Energized Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:3,amount:7,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:41465},
    {name: "Energized Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:3,amount:8,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:40105},
    {name: "Energized Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:3,amount:10,percentage:false}, {eid:12,amount:5,percentage:false}], wowhead_item_id:40179},

    {name: "Forceful Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:3,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39978},
    {name: "Perfect Forceful Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:3,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41466},
    {name: "Forceful Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:3,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40091},
    {name: "Forceful Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:3,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40169},

    {name: "Intricate Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:3,amount:6,percentage:false}, {eid:14,amount:6,percentage:false}], wowhead_item_id:39983},
    {name: "Perfect Intricate Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:3,amount:7,percentage:false}, {eid:14,amount:7,percentage:false}], wowhead_item_id:41467},
    {name: "Intricate Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:3,amount:8,percentage:false}, {eid:14,amount:8,percentage:false}], wowhead_item_id:40104},
    {name: "Intricate Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:3,amount:10,percentage:false}, {eid:14,amount:10,percentage:false}], wowhead_item_id:40174},

    {name: "Jagged Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:4,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39974},
    {name: "Perfect Jagged Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:4,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41468},
    {name: "Jagged Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:4,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40086},
    {name: "Jagged Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:4,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40165},

    {name: "Lambent Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:2,amount:6,percentage:false}, {eid:12,amount:3,percentage:false}], wowhead_item_id:39986},
    {name: "Perfect Lambent Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:2,amount:7,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:41469},
    {name: "Lambent Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:2,amount:8,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:40100},
    {name: "Lambent Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:2,amount:10,percentage:false}, {eid:12,amount:5,percentage:false}], wowhead_item_id:40177},

    {name: "Misty Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:4,amount:6,percentage:false}, {eid:14,amount:6,percentage:false}], wowhead_item_id:39980},
    {name: "Perfect Misty Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:4,amount:7,percentage:false}, {eid:14,amount:7,percentage:false}], wowhead_item_id:41470},
    {name: "Misty Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:4,amount:8,percentage:false}, {eid:14,amount:8,percentage:false}], wowhead_item_id:40095},
    {name: "Misty Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:4,amount:10,percentage:false}, {eid:14,amount:10,percentage:false}], wowhead_item_id:40171},

    {name: "Opaque Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:16,amount:6,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:39988},
    {name: "Perfect Opaque Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:16,amount:7,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:41471},
    {name: "Opaque Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:16,amount:8,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:40103},
    {name: "Opaque Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:16,amount:10,percentage:false}, {eid:12,amount:5,percentage:false}], wowhead_item_id:40178},
    
    {name: "Radiant Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:4,amount:6,percentage:false}, {eid:15,amount:8,percentage:false}], wowhead_item_id:39990},
    {name: "Perfect Radiant Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:4,amount:7,percentage:false}, {eid:15,amount:9,percentage:false}], wowhead_item_id:41472},
    {name: "Radiant Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:4,amount:8,percentage:false}, {eid:15,amount:10,percentage:false}], wowhead_item_id:40098},
    {name: "Radiant Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:4,amount:10,percentage:false}, {eid:15,amount:13,percentage:false}], wowhead_item_id:40180},

    {name: "Seer's Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:0,amount:6,percentage:false}, {eid:14,amount:6,percentage:false}], wowhead_item_id:39979},
    {name: "Perfect Seer's Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:0,amount:7,percentage:false}, {eid:14,amount:7,percentage:false}], wowhead_item_id:41473},
    {name: "Seer's Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:0,amount:8,percentage:false}, {eid:14,amount:8,percentage:false}], wowhead_item_id:40092},
    {name: "Seer's Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:0,amount:10,percentage:false}, {eid:14,amount:10,percentage:false}], wowhead_item_id:40170},

    {name: "Shattered Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:3,amount:6,percentage:false}, {eid:15,amount:8,percentage:false}], wowhead_item_id:39992},
    {name: "Perfect Shattered Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:3,amount:7,percentage:false}, {eid:15,amount:9,percentage:false}], wowhead_item_id:41474},
    {name: "Shattered Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:3,amount:8,percentage:false}, {eid:15,amount:10,percentage:false}], wowhead_item_id:40106},
    {name: "Shattered Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:3,amount:10,percentage:false}, {eid:15,amount:13,percentage:false}], wowhead_item_id:40182},

    {name: "Shining Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:2,amount:6,percentage:false}, {eid:14,amount:6,percentage:false}], wowhead_item_id:39981},
    {name: "Perfect Shining Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:2,amount:7,percentage:false}, {eid:14,amount:7,percentage:false}], wowhead_item_id:41475},
    {name: "Shining Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:2,amount:8,percentage:false}, {eid:14,amount:8,percentage:false}], wowhead_item_id:40099},
    {name: "Shining Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:2,amount:10,percentage:false}, {eid:14,amount:10,percentage:false}], wowhead_item_id:40172},

    {name: "Steady Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:16,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39977},
    {name: "Perfect Steady Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:16,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41476},
    {name: "Steady Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:16,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40090},
    {name: "Steady Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:16,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40168},

    {name: "Sundered Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:4,amount:6,percentage:false}, {eid:12,amount:3,percentage:false}], wowhead_item_id:39985},
    {name: "Perfect Sundered Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:4,amount:7,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:41477},
    {name: "Sundered Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:4,amount:8,percentage:false}, {eid:12,amount:4,percentage:false}], wowhead_item_id:40096},
    {name: "Sundered Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:4,amount:10,percentage:false}, {eid:12,amount:5,percentage:false}], wowhead_item_id:40176},

    {name: "Tense Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:2,amount:6,percentage:false}, {eid:15,amount:8,percentage:false}], wowhead_item_id:39991},
    {name: "Perfect Tense Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:2,amount:7,percentage:false}, {eid:15,amount:9,percentage:false}], wowhead_item_id:41478},
    {name: "Tense Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:2,amount:8,percentage:false}, {eid:15,amount:10,percentage:false}], wowhead_item_id:40101},
    {name: "Tense Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:2,amount:10,percentage:false}, {eid:15,amount:13,percentage:false}], wowhead_item_id:40181},

    {name: "Timeless Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:0,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39968},
    {name: "Perfect Timeless Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:0,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41479},
    {name: "Timeless Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:0,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40085},
    {name: "Timeless Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:0,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40164},

    {name: "Turbid Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:16,amount:6,percentage:false}, {eid:14,amount:6,percentage:false}], wowhead_item_id:39982},
    {name: "Perfect Turbid Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:16,amount:7,percentage:false}, {eid:14,amount:7,percentage:false}], wowhead_item_id:41480},
    {name: "Turbid Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:16,amount:8,percentage:false}, {eid:14,amount:8,percentage:false}], wowhead_item_id:40102},
    {name: "Turbid Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:16,amount:10,percentage:false}, {eid:14,amount:10,percentage:false}], wowhead_item_id:40173},

    {name: "Vivid Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:2,amount:6,percentage:false}, {eid:13,amount:9,percentage:false}], wowhead_item_id:39975},
    {name: "Perfect Vivid Dark Jade", socket_color:[1,2], gem_size:0, gem_stats:[{eid:2,amount:7,percentage:false}, {eid:13,amount:11,percentage:false}], wowhead_item_id:41481},
    {name: "Vivid Forest Emerald", socket_color:[1,2], gem_size:1, gem_stats:[{eid:2,amount:8,percentage:false}, {eid:13,amount:12,percentage:false}], wowhead_item_id:40088},
    {name: "Vivid Eye of Zul", socket_color:[1,2], gem_size:2, gem_stats:[{eid:2,amount:10,percentage:false}, {eid:13,amount:15,percentage:false}], wowhead_item_id:40166},

    {name: "Enchanted Pearl", socket_color:[0,1,2], gem_size:0, gem_stats:[{eid:5,amount:4,percentage:false}, {eid:7,amount:4,percentage:false}, {eid:0,amount:4,percentage:false},{eid:13,amount:4,percentage:false}, {eid:14,amount:4,percentage:false}], wowhead_item_id:42701},
    {name: "Enchanted Tear", socket_color:[0,1,2], gem_size:1, gem_stats:[{eid:5,amount:6,percentage:false}, {eid:7,amount:6,percentage:false}, {eid:0,amount:6,percentage:false},{eid:13,amount:6,percentage:false}, {eid:14,amount:6,percentage:false}], wowhead_item_id:42702},
    {name: "Nightmare Tear", socket_color:[0,1,2], gem_size:2, gem_stats:[{eid:5,amount:10,percentage:false}, {eid:7,amount:10,percentage:false}, {eid:0,amount:10,percentage:false},{eid:13,amount:10,percentage:false}, {eid:14,amount:10,percentage:false}], wowhead_item_id:49110},

    {name: "Austere Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:13,amount:32,percentage:false},{eid:19,amount:2,percentage:true}], wowhead_item_id:41380},
    {name: "Beaming Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:4,amount:21,percentage:false},{eid:20,amount:2,percentage:true}], wowhead_item_id:41389},
    {name: "Bracing Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:1,amount:25,percentage:false},{eid:33,amount:-2,percentage:true}], wowhead_item_id:41395},
    {name: "Chaotic Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:4,amount:21,percentage:false},{eid:21,amount:3,percentage:true}], wowhead_item_id:41285},
    {name: "Destructive Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:4,amount:25,percentage:false},{eid:22,amount:1,percentage:true}], wowhead_item_id:41307},
    {name: "Effulgent Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:13,amount:32,percentage:false},{eid:23,amount:-2,percentage:true}], wowhead_item_id:41377},
    {name: "Ember Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:1,amount:25,percentage:false},{eid:0,amount:2,percentage:true}], wowhead_item_id:41333},
    {name: "Enigmatic Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:4,amount:21,percentage:false},{eid:24,amount:-10,percentage:true}], wowhead_item_id:41335},
    {name: "Enigmatic Starflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:4,amount:17,percentage:false},{eid:24,amount:-10,percentage:true}], wowhead_item_id:44081},
    {name: "Eternal Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:17,amount:21,percentage:false},{eid:25,amount:5,percentage:true}], wowhead_item_id:41396},
    {name: "Forlorn Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:1,amount:25,percentage:false},{eid:26,amount:-10,percentage:true}], wowhead_item_id:41378},
    {name: "Forlorn Starflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:1,amount:20,percentage:false},{eid:26,amount:-10,percentage:true}], wowhead_item_id:44084},
    {name: "Impassive Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:4,amount:21,percentage:false},{eid:27,amount:-10,percentage:true}], wowhead_item_id:41379},
    {name: "Impassive Starflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:4,amount:17,percentage:false},{eid:27,amount:-10,percentage:true}], wowhead_item_id:44082},
    {name: "Insightful Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:0,amount:21,percentage:false},{eid:28,amount:5,percentage:true}], wowhead_item_id:41401},
    {name: "Invigorating Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:6,amount:42,percentage:false},{eid:29,amount:50,percentage:true}], wowhead_item_id:41385},
    {name: "Persistent Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:6,amount:42,percentage:false},{eid:30,amount:-10,percentage:true}], wowhead_item_id:41381},
    {name: "Persistent Earthshatter Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:6,amount:42,percentage:false},{eid:30,amount:-10,percentage:true}], wowhead_item_id:44087},
    {name: "Powerful Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:13,amount:32,percentage:false},{eid:30,amount:-10,percentage:true}], wowhead_item_id:41397},
    {name: "Powerful Earthshatter Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:13,amount:26,percentage:false},{eid:30,amount:-10,percentage:true}], wowhead_item_id:44088},
    {name: "Relentless Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:7,amount:21,percentage:false},{eid:21,amount:3,percentage:true}], wowhead_item_id:41398},
    {name: "Revitalizing Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:12,amount:11,percentage:false},{eid:31,amount:3,percentage:true}], wowhead_item_id:41376},
    {name: "Swift Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:6,amount:42,percentage:false},{eid:32,amount:8,percentage:true}], wowhead_item_id:41339},
    {name: "Swift Starflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:6,amount:34,percentage:false},{eid:32,amount:8,percentage:true}], wowhead_item_id:44076},
    {name: "Thundering Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:3,amount:64,percentage:false}], wowhead_item_id:41400, notes:"*Chance to Increase Melee/Ranged Attack Speed. 100% proc rate, 45s IC, 6s duration = ~64 perm haste"},
    {name: "Tireless Skyflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:1,amount:25,percentage:false},{eid:32,amount:8,percentage:true}], wowhead_item_id:41375},
    {name: "Tireless Starflare Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:1,amount:20,percentage:false},{eid:32,amount:8,percentage:true}], wowhead_item_id:44078},
    {name: "Trenchant Earthsiege Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:1,amount:25,percentage:false},{eid:30,amount:-10,percentage:true}], wowhead_item_id:41382},
    {name: "Trenchant Earthshatter Diamond", socket_color:[3], gem_size:4, gem_stats:[{eid:1,amount:20,percentage:false},{eid:30,amount:-10,percentage:true}], wowhead_item_id:44089},
];
